### ISSUE TITLE
Default fps should be 30 instead of 60

### ISSUE THREAD

**Issue by axu2** [AdmiralCurtiss/dgs_hackfix#11]
I installed this mod hoping it would stop my CPU fans from maxing out.

It didn't work by default, but setting 

```
AnimationFps = 30.0
```

did solve it.

Without the change, I was running at 1080p40 with extremely loud fans.

Now I'm running at 1080p30 with comfortable noise.

**Comment by AdmiralCurtiss** [comment]
The biggest reason I made this mod is *because* the original game only runs at 30 instead of the much more smooth 60. So no, I'm not changing that default. But since this is just a line in the settings go ahead and just change it to whatever you want, it's cool, I don't mind.

**Comment by AdmiralCurtiss** [comment]
(I suspect you're running this on a very low-performance CPU or GPU, in which case yeah you're definitely better off with the 30 FPS.)

**Comment by axu2** [comment]
Yes, I running this on a VERY low performance PC, maybe just add that as a note for those running low performance PCs.

**Comment by AdmiralCurtiss** [comment]
Sure, I can do that.

**Comment by axu2** [comment]
Thanks for letting me run this game on my old desktop from 2011!
