### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by chrisis123** [AdmiralCurtiss/dgs_hackfix#12]
Very small nitpicky thing wasn't sure I should even report this as an issue..
In the instrucations for Steamdeck it says dgs.ino but obviously should be dgs.ini

`Place the contents of the 'steamdeck' folder (dgs_hackfix.dll, dgs_patch_exe.exe, and dgs.ino) into same folder as TGAAC.exe`

Just tried to get it to run on Steamdeck yesterday and noticed the repo was updating.
So thank you for making this update works great. Danke und guats neues Jahr! :)

**Comment by AdmiralCurtiss** [comment]
Oops, yeah I'll fix that.
