### ISSUE TITLE
New game version broke the fix

### ISSUE THREAD

**Issue by ZxPat** [AdmiralCurtiss/dgs_hackfix#13]
Today a new game version was released and the mod doesn't seem to work anymore. 
This is the log
```
Found system DirectInput8Create at 0x00007ffb9f252230.
Allocation at 0x0000000063080000, base ptr 0x0000000063080000, size 0x1000, protection 0x2.
Allocation at 0x0000000063080000, base ptr 0x0000000063081000, size 0x13000, protection 0x20.
Allocation at 0x0000000063080000, base ptr 0x0000000063094000, size 0x6000, protection 0x2.
Allocation at 0x0000000063080000, base ptr 0x000000006309a000, size 0x4000, protection 0x8.
Allocation at 0x0000000063080000, base ptr 0x000000006309e000, size 0x4000, protection 0x2.
Allocation at 0x0000000140000000, base ptr 0x0000000140000000, size 0x1000, protection 0x2.
Allocation at 0x0000000140000000, base ptr 0x0000000140001000, size 0x953000, protection 0x20.
Checksum is 0xa9b1dc0f.
Could not identify code section.
Allocation at 0x0000000140000000, base ptr 0x0000000140954000, size 0x160000, protection 0x2.
Assuming 0x0000000140954000 as WW rdata section.
Allocation at 0x0000000140000000, base ptr 0x0000000140ab4000, size 0x14000, protection 0x8.
Allocation at 0x0000000140000000, base ptr 0x0000000140ac8000, size 0x1000, protection 0x4.
Allocation at 0x0000000140000000, base ptr 0x0000000140ac9000, size 0xca000, protection 0x8.
Allocation at 0x0000000140000000, base ptr 0x0000000140b93000, size 0x1000, protection 0x4.
Allocation at 0x0000000140000000, base ptr 0x0000000140b94000, size 0x2000, protection 0x8.
Allocation at 0x0000000140000000, base ptr 0x0000000140b96000, size 0x8f000, protection 0x2.
Allocation at 0x0000000140000000, base ptr 0x0000000140c25000, size 0x33000, protection 0x20.
Failed finding executable in memory -- wrong game or version?
```

**Comment by AdmiralCurtiss** [comment]
Lol what, they actually patched this? Shocking. I'll take a look when I have time.

**Comment by AdmiralCurtiss** [comment]
They added Steam DRM encryption????? Why do this two years after release???

**Comment by KatherineFtw** [comment]
So, does that mean we can use Steamless to fix it?

**Comment by AdmiralCurtiss** [comment]
Yes, you can unpack it with Steamless, but the unpacked binary will probably not match the expected memory layout for patching either if that's what you mean.

**Comment by ThePaSch** [comment]
There's a workaround that involves downgrading the game. Here's how it works:

1. **Open the Steam console**
If you're on Windows, you achieve this by pressing **WIN + R**, and entering `steam://open/console` into the Run dialog.
If you're on Linux/Steam Deck, you can do it by opening the System Terminal and running the command `steam steam://open/console` (note the extra `steam` in front of the command used for Windows).
Steam should open up and automatically navigate you to a normally hidden "Console" tab.

2. **Download the previous version**
In the Steam Console, run the following command:
`download_depot 1158850 1158852 4871682536058280805`
Steam will now download the files as they were in the game's initial launch state into a special directory. It might not confirm that it's doing so, there may be error messages, and there's not going to be a progress bar, but you can be certain that Steam is, indeed, downloading in the background.

3. **Disable auto-updates for TGAAC**
In the Steam client, right-click the entry for the game, select "Properties", navigate to the "Updates" tab, and, beneath the "Auomatic Updates" section, select the option that says "Only update this game when I launch it."

3. **Replace the game files**
When the depot download is finished, a new line will appear in the console, which will contain the path to the directory Steam has saved the depot files to. **Close Steam** - and make sure it's really closed and no longer running, not just minimized into the system tray. Then go to the directory that contains the depot files, copy all of its contents, and paste them into the game's main directory (should be `steamapps/common/TGAAC`. When you're asked whether you wish to replace files, confirm.
Your game is now downgraded to its initial launch version. However, Steam will likely just trigger an update the next time you try to launch the game, so we need to trick it into believing you have the latest version installed already.

4. **Lock the App Manifest**
In your `steamapps` directory, you will find a lot of files named `appmanifest_XXX.acf`, where XXX will be a number of arbitrary length. Find the file named `appmanifest_1158850.acf` and open it in a text editor (I recommend Notepad++ if you want it lightweight, or Visual Studio Code if not). Double-check that (a) the `BytesToDownload` value is equal to the `BytesDownloaded` value, and (b) the `manifest` value within the `1158852` entry is equal to `4559904711100554723`. This is what tells Steam that you have the latest version installed; however, these manifest files are frequently synchronized with the server and updated, so we need to prevent Steam from doing this. For that purpose, after double-checking that all values are as we would like them to be, just **set that file to read-only**. The file will no longer be updated, and Steam will be unable to detect that you're not running the latest version.

**Comment by AdmiralCurtiss** [comment]
> So, does that mean we can use Steamless to fix it?

> Yes, you can unpack it with Steamless, but the unpacked binary will probably not match the expected memory layout for patching either if that's what you mean.

So FYI, I tried this and it actually works, which makes the patch even more absurd. It looks like they didn't actually change the code at all, they just wrapped it in Steam's DRM for god knows what reason.

I've played around a bit and I'm a bit of a loss at how to transparently inject the patches into this thing. I would need to get control after Steam's DRM is done decrypting but before the game actually starts running, and I'm not really sure how to do that. I could ship Steamless to just decrypt the game on boot (and completely bypass Steam's decryptor) but that's not allowed by the Steamless license, so that's kinda out. I could tell the user to go download Steamless themselves to decrypt, and that works, but it's rather inconvenient compared to the previous just-drop-in-dll method...

**Comment by ayurai** [comment]
just so i understand, they literally just put drm and that is it with this patch?

**Comment by AdmiralCurtiss** [comment]
Okay, I figured out a workaround, it's pretty ugly (I'm racing against the decryption thread...) but it seems to work.

Download here: https://github.com/AdmiralCurtiss/dgs_hackfix/releases/tag/v11

I'll leave this open for another few hours in case anyone has problems with this release related to the patch.

**Comment by AdmiralCurtiss** [comment]
And yes,

> just so i understand, they literally just put drm and that is it with this patch?

As far as I can tell that's all they did.
