### ISSUE TITLE
Fix stopped working after recent updates on steam deck

### ISSUE THREAD

**Issue by Hakzource** [AdmiralCurtiss/dgs_hackfix#14]
No idea why, it worked before, but now even when i reinstall and try to configure the files it just won’t run at 60 FPS, it is stuck at a constant 30. Frame cap is 60 FPS on the deck too. (Doesn't even work on PC now, followed dl instructions to the word)

**Comment by AdmiralCurtiss** [comment]
You might be using the JP build, which was indeed broken after the update with v11. Try again with https://github.com/AdmiralCurtiss/dgs_hackfix/releases/tag/v12 and see if it works now; if you've used v10 before make sure to re-read the Steam Deck instructions as they are different to v10!

If it still doesn't work please post the log file.

**Comment by Hakzource** [comment]
Thanks for the fast update patch, v12 did indeed fix the issue of it not working at all. I’m honestly shocked despite not being in JP the build my region uses is that patch. Your patch is a godsend, thanks for all the hard work!

**Comment by AdmiralCurtiss** [comment]
Yeah, to clarify, there's two versions of this game depending on what region of the world you're in: The [WW Version](https://steamdb.info/depot/1158852/), which only includes English text, and the [JP Version](https://steamdb.info/depot/1158851/), which includes both English and Japanese text.
