### ISSUE TITLE
support Apollo Justice: Ace Attorney Trilogy

### ISSUE THREAD

**Issue by RA1NO3O** [AdmiralCurtiss/dgs_hackfix#15]
https://steamcommunity.com/app/2187220/discussions/0/5829413623761932020/

**Comment by AdmiralCurtiss** [comment]
I'm not gonna deal with Denuvo or any other garbage DRM Capcom puts into their games, sorry.

**Comment by AdmiralCurtiss** [comment]
~~For what it's worth, reading that thread, it sounds like it should be pretty trivial to just set up an injection dll that hooks a common function, forwards the call to the actual function, and occasionally writes a value to 0x2000080837C. If it's that easy I might end up doing it anyway, but if I have to end up injecting code like in DGS to fix other bugs in their engine I'm definitely not doing that with a code-obfuscating DRM...~~

e: In case anyone's come back to read this, apparently it's more complicated in this game to achieve correct high framerate play than just changing a value or two like it was in DGS, especially in the AA4 part of the collection. As such I'd have to actually patch the code, and doing that with a code-obfuscating DRM like Denuvo or Enigma in place is impractical. If/once the DRM is gone I can revisit this, but at the moment I'm afraid there isn't much I can do here.
