### ISSUE TITLE
Please considere a Apollo Justice Trilogy version

### ISSUE THREAD

**Issue by Schneitizel** [AdmiralCurtiss/dgs_hackfix#16]
Hi!
Apollo Justice: Ace Attorney Trilogy seems to have the same problem as TGAA: 3D game, stuck at 30fps...
Would it be possible to adapt this patch for Apollo Justice as well?

Thanks a lot!

**Comment by AdmiralCurtiss** [comment]
Like mentioned in #15, I have no interest in circumventing Capcom's silly DRM schemes in order to patch their code. Ping me again once they remove Denuvo and/or Enigma.

**Comment by RA1NO3O** [comment]
There's a possible way to archive this by using Cheat Engine, check the  steam community link I've mentioned at #15.
