### ISSUE TITLE
Patch won't apply or it crashes the game.

### ISSUE THREAD

**Issue by nathanielcwm** [AdmiralCurtiss/dgs_hackfix#4]
[dgsfix.log](https://github.com/AdmiralCurtiss/dgs_hackfix/files/6917005/dgsfix.log)

[config.txt](https://github.com/AdmiralCurtiss/dgs_hackfix/files/6917013/config.txt)
[env_option - Copy.txt](https://github.com/AdmiralCurtiss/dgs_hackfix/files/6917016/env_option.-.Copy.txt)

Game starts when loaded from steam but patch doesn't take effect
Game crashes immediately when started from executable

vcredist already installed and up to date at the time of writing this report.

Tested wtih v6 of patch

**Comment by nathanielcwm** [comment]
Downgrading to v5 and the issue still occurs.

**Comment by AdmiralCurtiss** [comment]
You're using the JP version of the executable, which I do not have support for. I would need someone to provide the equivalent addresses of the functions I'm patching in order to add support.

**Comment by AdmiralCurtiss** [comment]
The latest release (v7) should support the JP version of the game. Please try it out and report if it works!
