### ISSUE TITLE
Use existing CRC code in the game binary

### ISSUE THREAD

**Issue by wabberz** [AdmiralCurtiss/dgs_hackfix#9]
You can find MtCRC::getCRC() at 0x14033BD60 / 0x14033C800 if you want to remove the redundant code ;)

**Comment by AdmiralCurtiss** [comment]
Nice idea, but I can't exactly call code from the binary before I confirm that the binary is what I expect the binary to be, can I?

**Comment by wabberz** [comment]
Touché
